version: "3.9"
services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
  app:
    image: kotlin-rest-template:latest
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
